name: p26
version: 0.0.1
description: A minimal command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  sprintf: ">=1.0.8 <2.0.0"
dev_dependencies:
  unittest: any
